### PR TITLE
WIP: Make an installable Python package

### PR DESCRIPTION
**Pull request by MarcCote**
Since this PR involves moving a ton of files to `alfworld/` package, it is easier to look at the individual commits:

- f1642cea1b6080a26374978a6690976ef1d158ab
- 8dd6841e32fea5d4285d34cb7fede65d7675686a

TODO:
~~- [ ] Decide where should the data be downloaded? (Maybe, `$HOME/.alfworld` ?)~~ Added data downloader Python script. 
~~- [ ] Could we remove code duplication with ALFRED and use the alfred library instead? (This implies making ALFRED PyPi compatible, I can help).~~
- [ ] Test all the different scripts. @MohitShridhar can you point me towards the important ones?
- [ ] Update the README.md files such that they don't rely on ALFRED_ROOT

@MohitShridhar, I'll need your help to answer some of the questions above ^.

### CODE REVIEW

**Comment by MohitShridhar** [comment]
Thanks Marc! This looks great!

1. `$HOME/.alfworld` sounds good.
2. We made some custom modifications specifically for ALFWorld. It might be better to keep them separate.
3. Run the [training script](https://github.com/alfworld/alfworld/tree/master/agents#training) then the [eval script](https://github.com/alfworld/alfworld/tree/master/agents#evaluation) with the appropriate `load_from_tag` param. I can help you check this once it's ready.
4. Sure, I can take care of this

**Comment by MohitShridhar** [comment]
Let me know how I can test this before merging it into master.

**Comment by MarcCote** [comment]
I've worked more in this but haven't pushed my changes yet. Let's discuss it live Monday.

**Comment by MarcCote** [comment]
@MohitShridhar I did some testing. It seemed to work. I couldn't test the vision stuff on my laptop, though. Also, I haven't fixed the README.md yet.
Use the new data downloader in `scripts`.
Also, we need to merge this PR https://github.com/MohitShridhar/TextWorld/pull/2.

**Comment by MarcCote** [comment]
@MohitShridhar look at the different commits in this PR to see what changed (hopefully most commit names are self-explanatory).

**Comment by MarcCote** [comment]
@MohitShridhar alright. I added the option to use the var env "ALFWORLD_DATA" to specify where to save/load the data. I also changed setup.py to install the following scripts on the PATH: `alfworld-download`, `alfworld-play-thor`, and `alfworld-play-tw`.

**Comment by MarcCote** [comment]
@MohitShridhar I just checked your commits to this PR. They look good. Let me know when you want me to make a first pypi package for alfworld.

**Comment by MohitShridhar** [comment]
Thanks @MarcCote. I am updating the README with the new changes. I need to add some starter code for interacting with the environment like [this](https://github.com/MarcCote/TextWorld#playing-a-game-python--gym).

**Pull request merged**
